name: Update Item Types

on:
  push:
    branches:
      - main
    paths:
      - 'data/skins.json'
      - 'scripts/skins2type.py'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  update-types:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run type updater
      run: python scripts/skins2type.py

    - name: Commit changes
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/id2type.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update id2type.json"
        git push